theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

lang: FR

title: Mon étoile polaire
description: Mélanie Comte, thérapeute, certifiée méthodes PEAT

meta_title: Thérapeute, méthodes PEAT | Mélanie Comte
meta_description: 
meta_keywords: peat, thérapeute, gestion du stress
