theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

lang: FR

title: Mon étoile polaire
description: Mélanie Comte, thérapeute, certifiée méthodes PEAT

# meta_title: title
# meta_description: description
# meta_keywords: keywords
