theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

lang: FR

title: Mélanie Comte
description: Mon étoile polaire

show_downloads: false

# meta_title: 
# meta_description: 
# meta_keywords: 
